---
repository_url: https://github.com/shahabkamali/MeteorCloud.git
git_ref: master
image_source: git
backend_image: edge-platform-backend:0.2.0
frontend_image: edge-platform-frontend:0.2.0
platform_public_url: http://127.0.0.1
postgres_database: edge_platform
postgres_username: edge_platform
platform_env: production
platform_version: "0.2.0"
platform_domain: ""
